.git
.gitignore
.pytest_cache
.venv
venv
__pycache__
*.pyc
.env
.env.*

device/
docs/
provision_backend/
platform/backend/
platform/infra/
platform/mobile/
platform/shared/

platform/web/dist/
platform/web/node_modules/
platform/web/.env
platform/web/.env.*
platform/web/tsconfig.tsbuildinfo
