import type { ImageSourcePropType } from "react-native";

export const evtAssets = {
  accountIcon: require("../../assets/evt/account-icon.png") as ImageSourcePropType,
  appleIcon: require("../../assets/evt/apple-icon.png") as ImageSourcePropType,
  authLeafFrame: require("../../assets/evt/auth-leaf-frame.png") as ImageSourcePropType,
  cameraIcon: require("../../assets/evt/camera-icon.png") as ImageSourcePropType,
  caseIcon: require("../../assets/evt/case-icon.png") as ImageSourcePropType,
  dataIcon: require("../../assets/evt/data-icon.png") as ImageSourcePropType,
  deviceTabIcon: require("../../assets/evt/device-tab-icon.png") as ImageSourcePropType,
  eyeIcon: require("../../assets/evt/eye-icon.png") as ImageSourcePropType,
  googleIcon: require("../../assets/evt/google-icon.png") as ImageSourcePropType,
  humiditySparkline: require("../../assets/evt/humidity-sparkline.png") as ImageSourcePropType,
  lockIcon: require("../../assets/evt/lock-icon.png") as ImageSourcePropType,
  notificationIcon: require("../../assets/evt/notification-icon.png") as ImageSourcePropType,
  plantIdentificationIcon: require("../../assets/evt/plant-identification-icon.png") as ImageSourcePropType,
  plantOutlineIcon: require("../../assets/evt/plant-outline-icon.png") as ImageSourcePropType,
  plantLabLeafLogo: require("../../assets/evt/plantlab-leaf-logo.png") as ImageSourcePropType,
  plantLabWordmark: require("../../assets/evt/plantlab-wordmark.png") as ImageSourcePropType,
  homeIcon: require("../../assets/evt/home-icon.png") as ImageSourcePropType,
  settingsTabIcon: require("../../assets/evt/settings-tab-icon.png") as ImageSourcePropType,
  supportTabIcon: require("../../assets/evt/support-tab-icon.png") as ImageSourcePropType,
  waterLevelSparkline: require("../../assets/evt/water-level-sparkline.png") as ImageSourcePropType,
} as const;

export const evtAssetMapping = [
  ["image 93.png", "auth-leaf-frame.png"],
  ["Group 117.png", "plantlab-leaf-logo.png"],
  ["Group 144.png", "plantlab-wordmark.png"],
  ["pngsucai_1395069_3c5c6c 1.png", "google-icon.png"],
  ["Vector.png", "apple-icon.png"],
  ["Frame-1.png", "account-icon.png"],
  ["Frame-2.png", "lock-icon.png"],
  ["Frame.png", "eye-icon.png"],
  ["brand.png", "notification-icon.png"],
  ["Group 106.png", "plant-identification-icon.png"],
  ["Group 118-2.png", "camera-icon.png"],
  ["Humidity sparkline.png", "humidity-sparkline.png"],
  ["Water Level sparkline.png", "water-level-sparkline.png"],
  ["image 90.png", "plant-outline-icon.png"],
  ["Group-1.png", "home-icon.png"],
  ["Vector-4.png", "case-icon.png"],
  ["Frame 157-1.png", "data-icon.png"],
  ["Frame 290.png", "device-tab-icon.png"],
  ["Frame 157.png", "settings-tab-icon.png"],
  ["Frame 157-1.png", "support-tab-icon.png"],
] as const;
