const colors = {
  background: "#fbfcfb",
  backgroundElevated: "#eef3f1",
  screenBackground: "#fbfcfb",
  surface: "#ffffff",
  cardBackground: "#ffffff",
  surfaceMuted: "#f8faf9",
  surfaceInset: "#f1f5f4",
  border: "#e5e8e4",
  borderSoft: "#eef0ed",
  divider: "#eeeeee",
  accent: "#69b56f",
  primaryGreen: "#69b56f",
  secondaryGreen: "#8ab87c",
  darkGreen: "#437b48",
  accentSoft: "#eef8ef",
  textPrimary: "#303030",
  darkText: "#303030",
  textSecondary: "#777f78",
  secondaryText: "#777f78",
  textMuted: "#a2a7a3",
  mutedText: "#a2a7a3",
  white: "#ffffff",
  success: "#60b865",
  successSoft: "#eaf8ec",
  warning: "#f6a11a",
  warningSoft: "#fff7e8",
  danger: "#b42318",
  dangerStrong: "#d92d20",
  dangerSoft: "#fde4e4",
  info: "#175cd3",
  infoSoft: "#e8f1ff",
  mock: "#6941c6",
  mockSoft: "#efe7ff",
  chartGrid: "#dbe4e0",
  chartAxis: "#7a8a83",
  sensorAir: "#b76a35",
  sensorHumidity: "#2f75b5",
  sensorWater: "#2f855a",
  sensorWaterLevel: "#30aeea",
  sensorLight: "#f6a11a",
  lavender: "#7867f4",
};

export const theme = {
  colors,
  status: {
    online: { text: colors.success, background: colors.successSoft, border: "#b9e8c7" },
    degraded: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    offline: { text: colors.textMuted, background: colors.surfaceInset, border: colors.border },
    provisioning: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    updating: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    error: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
    mock: { text: colors.mock, background: colors.mockSoft, border: "#dac7ff" },
  },
  severity: {
    info: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    warning: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    critical: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
  },
  health: {
    healthy: { text: colors.success, background: colors.successSoft, border: "#b9e8c7" },
    attention: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    offline: { text: colors.textMuted, background: colors.surfaceInset, border: colors.border },
    updating: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    critical: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
  },
  surfaces: {
    default: { backgroundColor: colors.surface, borderColor: colors.border },
    muted: { backgroundColor: colors.surfaceMuted, borderColor: colors.borderSoft },
    inset: { backgroundColor: colors.surfaceInset, borderColor: colors.borderSoft },
    hero: { backgroundColor: colors.surface, borderColor: colors.borderSoft },
    debug: { backgroundColor: colors.surfaceMuted, borderColor: colors.border },
  },
  elevation: {
    none: {
      shadowOpacity: 0,
      elevation: 0,
    },
    card: {
      shadowColor: "#000000",
      shadowOpacity: 0.05,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    hero: {
      shadowColor: "#000000",
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 3,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    page: 16,
  },
  radii: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
    pill: 999,
  },
  typography: {
    eyebrow: 12,
    caption: 12,
    meta: 13,
    body: 14,
    bodyLarge: 16,
    sectionTitle: 18,
    cardTitle: 20,
    screenTitle: 30,
  },
  evtTypography: {
    tiny: 10,
    caption: 11,
    meta: 12,
    body: 13,
    bodyLarge: 14,
    sectionTitle: 15,
    title: 20,
    hero: 28,
  },
  evtShadow: {
    shadowColor: "#27372b",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  motion: {
    fastMs: 120,
    normalMs: 180,
    slowMs: 260,
  },
} as const;
