const colors = {
  background: "#f5f7f8",
  backgroundElevated: "#eef3f1",
  surface: "#ffffff",
  surfaceMuted: "#f8faf9",
  surfaceInset: "#f1f5f4",
  border: "#d7dee3",
  borderSoft: "#e6ece9",
  accent: "#2f855a",
  accentSoft: "#e7f3ec",
  textPrimary: "#1f2a24",
  textSecondary: "#55635d",
  textMuted: "#708078",
  white: "#ffffff",
  success: "#157347",
  successSoft: "#dff7e8",
  warning: "#9a6700",
  warningSoft: "#fff1d6",
  danger: "#b42318",
  dangerStrong: "#d92d20",
  dangerSoft: "#fde4e4",
  info: "#175cd3",
  infoSoft: "#e8f1ff",
  mock: "#6941c6",
  mockSoft: "#efe7ff",
  chartGrid: "#dbe4e0",
  chartAxis: "#7a8a83",
  sensorAir: "#b76a35",
  sensorHumidity: "#2f75b5",
  sensorWater: "#2f855a",
};

export const theme = {
  colors,
  status: {
    online: { text: colors.success, background: colors.successSoft, border: "#b9e8c7" },
    degraded: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    offline: { text: colors.textMuted, background: colors.surfaceInset, border: colors.border },
    provisioning: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    updating: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    error: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
    mock: { text: colors.mock, background: colors.mockSoft, border: "#dac7ff" },
  },
  severity: {
    info: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    warning: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    critical: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
  },
  health: {
    healthy: { text: colors.success, background: colors.successSoft, border: "#b9e8c7" },
    attention: { text: colors.warning, background: colors.warningSoft, border: "#f4d99a" },
    offline: { text: colors.textMuted, background: colors.surfaceInset, border: colors.border },
    updating: { text: colors.info, background: colors.infoSoft, border: "#c5d8ff" },
    critical: { text: colors.danger, background: colors.dangerSoft, border: "#f3b8b8" },
  },
  surfaces: {
    default: { backgroundColor: colors.surface, borderColor: colors.border },
    muted: { backgroundColor: colors.surfaceMuted, borderColor: colors.borderSoft },
    inset: { backgroundColor: colors.surfaceInset, borderColor: colors.borderSoft },
    hero: { backgroundColor: colors.surface, borderColor: colors.borderSoft },
    debug: { backgroundColor: colors.surfaceMuted, borderColor: colors.border },
  },
  elevation: {
    none: {
      shadowOpacity: 0,
      elevation: 0,
    },
    card: {
      shadowColor: "#000000",
      shadowOpacity: 0.05,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    hero: {
      shadowColor: "#000000",
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 3,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radii: {
    sm: 6,
    md: 8,
    pill: 999,
  },
  typography: {
    eyebrow: 12,
    caption: 12,
    meta: 13,
    body: 14,
    bodyLarge: 16,
    sectionTitle: 18,
    cardTitle: 20,
    screenTitle: 30,
  },
  motion: {
    fastMs: 120,
    normalMs: 180,
    slowMs: 260,
  },
} as const;
